@startuml
' !include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean/puml-theme-cerulean.puml
start
partition Preparation {
    :Requirements Analysis (week7~8);
    :UML Drawing (week9~10);
}
partition Design {
    :System Design (week11~12);
    :Program Design (week13~14);
}
partition Implemantation&Test {
    :Implemantation (week15~16);
    :Testing (week17~18);
}

stop

legend center
Flow Diagram for Delivery Schedule
endlegend
@enduml