' 用户发出加入考试的请求后，系统会用户的身份和权限进行检测，检查成功后。更新用户的临时权限，建立用户和考试页面的连接，此后用户即可在前端通过考试页面进行答题，答题结果通过通信协议传输给批改程序进行批改，最终结果反馈给教学者和学习者。
@startuml
' left to right direction
actor student as st
package Frontend {
    usecase "Interface" as inter
    usecase "Exam Component" as ec
}
package Backend {
    usecase "User Database" as ud
    usecase "Server Node" as sn
    usecase "Correcting Node" as cn

}
st --> inter: "Begin Exam"
st --> inter: "Write Answer"
inter --> ec: "Join Exam"
inter --> ec: "Transfer Exam"
ec --> sn: "Joining Exam Request"
ec --> sn: "File Transferring(SSH/HTTP)"
sn --> ud: "Query User Permission"
' sn --> fd: "Store File"
ud --> sn: "Query Result"
sn --> ec: "Joining Response"
ec --> inter: "Joining Response"
inter --> st: "Display Exam Paper"
sn --> cn: "Exam Paper"
cn --> sn: "Exam Result"
sn --> ec: "Exam Result"
ec --> inter: "Exam Result"
inter --> st: "Display Exam Result"

@enduml

