' 自由开发者在开发页面根据指引在本地安装开发工具包(SDK)，该工具包将使用主流的编程框架作为技术支撑，实现在本地模拟线上环境测试的功能。在根据开发文档完成开发和测试后在开发页面提交打包好的题目，系统将其加入审核队列，题目审核员对题目按先后顺序审核，审核通过后将题目加入数据库上线。
@startuml
' left to right direction
actor developer as de
actor reviewer as re
package Frontend {
    usecase "Interface" as inter
    usecase "Problem Component" as pc
}
package Backend {
  usecase "File Database" as fd
  usecase "Server Node" as sn
  usecase "Review Queue" as rq
}
de --> inter: "Submit Problem"
inter --> pc: "Transfer Problem"
pc --> sn: "File Transferring(SSH/HTTP)"
sn --> rq: "Problem to be Reviewd"
rq --> re: "Problem to be Reviewd"
re --> rq: "Reviewd Result"
rq --> sn: "Reviewd Result"
sn --> fd: "Store Problem"
sn --> pc: "Reviewd Result"
pc --> inter: "Reviewd Result"
inter --> de: "Display Result"
@enduml